require "tools"

hs.hotkey.bind(hyper, "d", launchOrCycleFocus("com.apple.Safari"))
hs.hotkey.bind(hyper, "e", launchOrToggle("Calendar"))
hs.hotkey.bind(hyper, "c", launchOrToggle("Slack"))
hs.hotkey.bind(hyper, "f", launchOrCycleFocus("com.apple.finder"))
hs.hotkey.bind(hyper, "m", launchOrToggle("Mail"))
hs.hotkey.bind(hyper, "i", launchOrToggle("iTunes"))
hs.hotkey.bind(hyper, "t", launchOrToggle("iTerm"))
hs.hotkey.bind(hyper, "g", launchOrToggle("Tower"))
hs.hotkey.bind(hyper, "w", launchOrToggleByBundleId("com.culturedcode.ThingsMac"))
-- hs.hotkey.bind(hyper, "w", launchOrToggle("Reminders"))
hs.hotkey.bind(hyper, "s", launchOrToggle("Notes"))
hs.hotkey.bind(hyper, "x", launchOrCycleFocus("com.apple.dt.Xcode"))
hs.hotkey.bind(hyper, "v", launchOrCycleFocus("com.microsoft.VSCode"))
hs.hotkey.bind(hyperShift, "x", launchOrToggle("Simulator"))
hs.hotkey.bind(hyper, "n", launchOrToggle("Messages"))
