require "tools"

hs.hotkey.bind(hyper, "d", launchOrCycleFocus("Safari"))
hs.hotkey.bind(hyper, "e", launchOrCycleFocus("Calendar"))
hs.hotkey.bind(hyper, "c", launchOrToggle("Slack"))
hs.hotkey.bind(hyper, "f", launchOrCycleFocus("Finder"))
hs.hotkey.bind(hyper, "m", launchOrCycleFocus("Mail"))
hs.hotkey.bind(hyper, "i", launchOrCycleFocus("iTunes"))
-- hs.hotkey.bind(hyper, "t", launchOrCycleFocus("iTerm"))
hs.hotkey.bind(hyper, "g", launchOrToggle("Tower"))
hs.hotkey.bind(hyper, "w", launchOrToggle("2Do"))
hs.hotkey.bind(hyper, "s", launchOrToggle("Notes"))
hs.hotkey.bind(hyper, "x", launchOrCycleFocus("XCode"))
hs.hotkey.bind(hyper, "a", launchOrCycleFocus("Atom"))
hs.hotkey.bind(hyper, "z", launchOrToggle("Simulator"))
hs.hotkey.bind(hyper, "n", launchOrToggle("Messages"))
